# MySQL. Versions 5.6.4 and up are supported.
#
# Install the MySQL driver:
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile:
#   gem "mysql2"
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "Harish123") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: book_my_show_development

test:
  <<: *default
  database: book_my_show_test
  # Overriding password in CI if needed
  username: <%= ENV.fetch("DB_USERNAME", "root") %>
  password: <%= ENV.fetch("DB_PASSWORD", "Harish123") %>

production:
  primary: &primary_production
    <<: *default
    database: book_my_show_production
    username: <%= ENV.fetch("BOOK_MY_SHOW_DATABASE_USERNAME", "book_my_show") %>
    password: <%= ENV["BOOK_MY_SHOW_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: book_my_show_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: book_my_show_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: book_my_show_production_cable
    migrations_paths: db/cable_migrate
